language: C
install: make cmake
compiler:
  - clang
  - gcc
script:
  - cmake -DSANITIZE_ADDRESS=On -DSANITIZE_UNDEFINED=On . && make && make test && gcov src/CMakeFiles/cfifo.dir/cfifo.c.gcno 

after_success:
  - bash <(curl -s https://codecov.io/bash)